### ISSUE TITLE
<compileSource>

### ISSUE THREAD

**Issue by OliverJAsh** [trungfinity/traceur-source-maps#5]
My stack traces are resolved, but the filenames are just displayed as `<compileSource>`. E.g.:

```
     TypeError: Object #<FeedItemModel> has no method 'toJS'
      at MongoDbService.create (/Users/Oliver/Development/sbscribe/sbscribe-services/lib/<compileSource>:28:65)
      at MongoDbService.Service.service.create (/Users/Oliver/Development/sbscribe/sbscribe-services/services/feed-item/<compileSource>:21:46)
      at it.only.setup.rootResource.follow.feedUrl (/Users/Oliver/Development/sbscribe/sbscribe-api/test/endpoints/<compileSource>:266:39)
      at _fulfilled (/Users/Oliver/Development/sbscribe/sbscribe-services/node_modules/q/q.js:787:66)
      at self.promiseDispatch.done (/Users/Oliver/Development/sbscribe/sbscribe-services/node_modules/q/q.js:816:42)
      at Promise.promise.promiseDispatch (/Users/Oliver/Development/sbscribe/sbscribe-services/node_modules/q/q.js:749:25)
      at /Users/Oliver/Development/sbscribe/sbscribe-services/node_modules/q/q.js:557:60
      at flush (/Users/Oliver/Development/sbscribe/sbscribe-services/node_modules/q/q.js:108:33)
      at process._tickDomainCallback (node.js:463:13)
```

Is this a bug?

**Comment by trungfinity** [comment]
Thanks for reporting!

This is a bug reported and fixed in #4. I pushed the patch to `npm` as version 1.0.4.
